server:
  port: 8080
  error:
    whitelabel:
      enabled: false   # Disable the default Spring Boot error page
    include-message: always  # Include exception messages in error responses (for debugging)

spring:
  application:
    name: kassensystem

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG  # See web requests in the console
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

